FROM node:24.10.0-alpine

RUN apk add --no-cache python3 py3-pip && \
  npm install -g tsx

WORKDIR /app

# * copy wrapper
COPY internal/resource/wrapper.js /app/wrapper.js
COPY internal/resource/wrapper.py /app/wrapper.py
COPY internal/resource/wrapper.ts /app/wrapper.ts

CMD ["sleep", "infinity"]